// sdd-kit: managed file. Do not edit; local changes are overwritten on kit update.
// Runs a change's verification from openspec/tooling/verify.yaml and builds verification.md from REAL
// results: a row is `Met` only when every test carrying its scenario marker at that level passed.
// Manual rows keep the verdict a human wrote. (openspec/protocols/testing.md §6)
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { loadVerifyConfig } from './verify-config.mjs';
import { parseResults } from './results.mjs';
import { parsePlan, parseVerification, key } from './plan.mjs';
import { loadChangeDeltas, changeScenarios } from './spec-parser.mjs';
import { changeDir, readChangeFile } from './project.mjs';
import { fingerprint, writeState } from './state.mjs';

const SAFE_ID = /^[^'"`$\\;&|<>\n]+$/;
const TAIL_LINES = 40;

export class VerifyError extends Error {}

function tail(text, n = TAIL_LINES) {
  const lines = String(text || '').trimEnd().split('\n');
  return lines.slice(-n).join('\n');
}

/** Runs one shell command from verify.yaml. `files` fills {files}; {out} gets a fresh temp file. */
export function runCommand(root, template, { files = [], timeoutSeconds = 1800 } = {}) {
  for (const f of files) if (!SAFE_ID.test(f)) throw new VerifyError(`test id cannot be passed to a shell command safely: ${f}`);
  const dir = mkdtempSync(join(tmpdir(), 'sdd-kit-run-'));
  const out = join(dir, 'out.json');
  const cmd = template.replaceAll('{out}', out).replaceAll('{files}', files.join(' '));
  const t0 = Date.now();
  const r = spawnSync('sh', ['-c', cmd], { cwd: root, encoding: 'utf8', timeout: timeoutSeconds * 1000, maxBuffer: 256 * 1024 * 1024 });
  const res = {
    cmd,
    template,
    exitCode: r.status ?? (r.signal ? 128 : 1),
    timedOut: Boolean(r.error && r.error.code === 'ETIMEDOUT'),
    durationMs: Date.now() - t0,
    stdout: r.stdout || '',
    stderr: r.stderr || '',
    output: template.includes('{out}') ? (existsSync(out) ? readFileSync(out, 'utf8') : null) : r.stdout || '',
  };
  rmSync(dir, { recursive: true, force: true });
  return res;
}

function thenText(body) {
  const lines = body
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => /^[-*]\s*\*\*(THEN|AND)\*\*/.test(l))
    .map((l) => l.replace(/^[-*]\s*\*\*(THEN|AND)\*\*\s*/, ''));
  return lines.join('; ');
}

const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim() || '—';

/** Markdown of verification.md. */
export function renderVerification(rows, commands) {
  const out = [
    '<!-- Generated by sdd-kit verify (node openspec/tooling/bin/verify.mjs). Automated rows are rewritten on every',
    '     run from real test results; manual rows keep the verdict and evidence a human writes into them. -->',
    '## Verification matrix',
    '',
    '| Capability | Scenario | Level | Expected | Actual | Evidence | Verdict |',
    '|---|---|---|---|---|---|---|',
    ...rows.map((r) => `| ${cell(r.capability)} | ${cell(r.scenario)} | ${cell(r.level)} | ${cell(r.expected)} | ${cell(r.actual)} | ${cell(r.evidence)} | ${r.verdict} |`),
    '',
    '## Commands run',
    '',
    ...commands.map((c) => `- \`${c.template}\` — exit ${c.exitCode}${c.timedOut ? ' (timed out)' : ''}, ${(c.durationMs / 1000).toFixed(1)} s${c.summary ? ` — ${c.summary}` : ''}`),
    '',
  ];
  return out.join('\n');
}

function summarise(results) {
  const n = { passed: 0, failed: 0, error: 0, skipped: 0 };
  const seen = new Set();
  for (const r of results) {
    if (!r.outcome || seen.has(r.test)) continue;
    seen.add(r.test);
    n[r.outcome] = (n[r.outcome] || 0) + 1;
  }
  return `marked tests: ${n.passed} passed, ${n.failed + n.error} failed, ${n.skipped} skipped`;
}

/**
 * Verifies a change. Options: { root, change, mode: 'full'|'scoped', write: boolean, e2e: 'scoped'|'full'|'off'|undefined,
 * cache?: Map } — with a shared `cache`, identical commands (e.g. the full suite) run once for several changes.
 * Returns { ok, complete, rows, commands, markers, manualPending, fingerprint, problems }.
 */
export function runVerification({ root, change, mode = 'full', write = true, e2e, cache = null }) {
  const cfg = loadVerifyConfig(root);
  if (!cfg) throw new VerifyError('openspec/tooling/verify.yaml does not exist — configure the project test commands first (sdd-kit install --preset …)');
  const dir = changeDir(root, change);
  if (!existsSync(dir)) throw new VerifyError(`change "${change}" not found`);
  const planText = readChangeFile(root, change, 'verification-plan.md');
  if (planText === null) throw new VerifyError(`change "${change}" has no verification-plan.md`);
  const plan = parsePlan(planText);
  const deltas = loadChangeDeltas(root, dir);
  const scenarios = new Map(changeScenarios(deltas).map((s) => [key(s.capability, s.scenario), s]));
  const bodies = new Map();
  for (const { capability, delta } of deltas) for (const r of [...delta.added, ...delta.modified]) for (const s of r.scenarios) bodies.set(key(capability, s.name), s.body);

  const commands = [];
  const problems = [];
  const results = []; // all rows from all levels (whole project)
  const e2eMode = e2e || cfg.gates.e2e;
  const changeKeys = new Set(plan.coverage.rows.map((r) => key(r.capability, r.scenario)));
  const plannedAt = (level) => plan.coverage.rows.some((r) => r.level === level);

  const cached = (template, files, fn) => {
    const k = `${template}\u0000${(files || []).join(' ')}`;
    if (!cache) return fn();
    if (!cache.has(k)) cache.set(k, fn());
    return cache.get(k);
  };
  const exec = (template, files) => cached(template, files, () => runCommand(root, template, { files: files || [], timeoutSeconds: cfg.timeout_seconds }));
  const collect = (level, l) => {
    const c = exec(l.collect, null);
    commands.push({ ...c, name: `${level} collect`, summary: c.exitCode === 0 ? '' : 'collection failed' });
    if (c.exitCode !== 0 || c.output === null) {
      problems.push(`${level} collect failed (exit ${c.exitCode}):\n${tail(c.stdout + c.stderr)}`);
      return [];
    }
    return parseResults(c.output, l.format, level, root);
  };
  const run = (level, l, template, files) => {
    const c = exec(template, files);
    let rows = [];
    try {
      rows = c.output ? parseResults(c.output, l.format, level, root) : [];
    } catch (e) {
      problems.push(`${level}: cannot read results — ${e.message}`);
    }
    commands.push({ ...c, name: `${level} ${files ? 'scoped' : 'full'}`, summary: rows.length ? summarise(rows) : c.output === null ? 'no results file written' : '' });
    if (c.exitCode !== 0) problems.push(`\`${template}\` failed (exit ${c.exitCode}${c.timedOut ? ', timed out' : ''}):\n${tail(c.stdout + '\n' + c.stderr)}`);
    results.push(...rows);
  };

  const unit = cfg.levels.unit;
  if (unit) {
    if (mode === 'scoped' && unit.scoped) {
      const files = [...new Set(collect('unit', unit).filter((m) => changeKeys.has(key(m.capability, m.scenario))).map((m) => m.test))];
      if (files.length) run('unit', unit, unit.scoped, files);
    } else {
      run('unit', unit, unit.full, null);
    }
    if (unit.gate && mode !== 'scoped') {
      const g = exec(unit.gate, null);
      commands.push({ ...g, name: 'quality gate', summary: '' });
      if (g.exitCode !== 0) problems.push(`quality gate \`${unit.gate}\` failed (exit ${g.exitCode}):\n${tail(g.stdout + '\n' + g.stderr)}`);
    }
  } else if (plannedAt('unit')) problems.push('verification-plan.md plans unit tests but verify.yaml has no "unit" level');

  const e2eCfg = cfg.levels.e2e;
  if (e2eCfg && e2eMode !== 'off' && (plannedAt('e2e') || e2eMode === 'full')) {
    if (e2eMode === 'scoped' && e2eCfg.scoped) {
      const files = [...new Set(collect('e2e', e2eCfg).filter((m) => changeKeys.has(key(m.capability, m.scenario))).map((m) => m.file))];
      if (files.length) run('e2e', e2eCfg, e2eCfg.scoped, files);
    } else {
      run('e2e', e2eCfg, e2eCfg.full, null);
    }
  } else if (!e2eCfg && plannedAt('e2e')) problems.push('verification-plan.md plans e2e tests but verify.yaml has no "e2e" level');

  // matrix
  const previous = readChangeFile(root, change, 'verification.md');
  const manualPrev = new Map();
  if (previous) for (const r of parseVerification(previous).matrix.rows) if (r.level === 'manual') manualPrev.set(key(r.capability, r.scenario), r);
  const ranLevels = new Set(results.map((r) => r.level));
  const rows = plan.coverage.rows.map((p) => {
    const k = key(p.capability, p.scenario);
    const expected = bodies.has(k) ? thenText(bodies.get(k)) : '';
    if (p.level === 'manual') {
      const m = manualPrev.get(k);
      if (m && ['Met', 'Not Met'].includes(m.verdict)) return { ...p, expected: m.expected || expected, actual: m.actual, evidence: m.evidence, verdict: m.verdict };
      return { ...p, expected, actual: 'manual check pending', evidence: '—', verdict: 'Unverified' };
    }
    const tests = results.filter((r) => r.level === p.level && key(r.capability, r.scenario) === k && r.outcome);
    if (!scenarios.has(k)) return { ...p, expected, actual: 'scenario not in the delta specs', evidence: '—', verdict: 'Unverified' };
    if (!tests.length) {
      return { ...p, expected, actual: ranLevels.has(p.level) ? `no ${p.level} test carries this scenario marker` : `${p.level} tests did not run`, evidence: '—', verdict: 'Unverified' };
    }
    const bad = tests.filter((t) => t.outcome === 'failed' || t.outcome === 'error');
    const passed = tests.filter((t) => t.outcome === 'passed');
    const list = (ts) => ts.slice(0, 3).map((t) => t.test).join(', ') + (ts.length > 3 ? ` (+${ts.length - 3})` : '');
    if (bad.length) return { ...p, expected, actual: `${bad.length} test(s) failed`, evidence: `failed: ${list(bad)}`, verdict: 'Not Met' };
    if (!passed.length) return { ...p, expected, actual: 'all marked tests were skipped', evidence: `skipped: ${list(tests)}`, verdict: 'Unverified' };
    return { ...p, expected, actual: 'as expected', evidence: `${passed.length} passed: ${list(passed)}`, verdict: 'Met' };
  });

  const commandsOk = commands.every((c) => c.exitCode === 0) && !problems.length;
  const automatedOk = rows.filter((r) => r.level !== 'manual').every((r) => r.verdict === 'Met');
  const manualPending = rows.filter((r) => r.level === 'manual' && r.verdict !== 'Met');
  const markers = results.filter((r) => changeKeys.has(key(r.capability, r.scenario)) || scenarios.has(key(r.capability, r.scenario)));
  const fp = fingerprint(root, change);
  const result = { change, mode, ok: commandsOk && automatedOk, complete: commandsOk && automatedOk && !manualPending.length, rows, commands: commands.map(({ stdout, stderr, output, ...c }) => c), markers, manualPending, problems, fingerprint: fp };
  if (write) {
    writeFileSync(join(dir, 'verification.md'), renderVerification(rows, commands));
    if (mode === 'full') {
      writeState(root, `verify-${change}`, {
        fingerprint: fp,
        ok: result.ok,
        complete: result.complete,
        manualPending: manualPending.map((m) => `${m.scenario} (${m.capability})`),
        markers,
        at: new Date().toISOString(),
      });
    }
  }
  return result;
}

/**
 * Markers only (no test run): runs each configured level's `collect` command. Used by CI for changes that
 * are still in progress. Returns { markers, problems }.
 */
export function collectMarkers({ root, cache = null }) {
  const cfg = loadVerifyConfig(root);
  if (!cfg) throw new VerifyError('openspec/tooling/verify.yaml does not exist');
  const markers = [];
  const problems = [];
  for (const [level, l] of Object.entries(cfg.levels)) {
    const k = `${l.collect}\u0000`;
    const c = cache?.get(k) || runCommand(root, l.collect, { timeoutSeconds: cfg.timeout_seconds });
    if (cache && !cache.has(k)) cache.set(k, c);
    if (c.exitCode !== 0 || c.output === null) {
      problems.push(`${level} collect failed (exit ${c.exitCode}):\n${tail(c.stdout + c.stderr)}`);
      continue;
    }
    markers.push(...parseResults(c.output, l.format, level, root));
  }
  return { markers, problems };
}
